apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "mywebapp"
spec:
  template:
    spec:
      containers:
        - name: "mywebapp"
          resources:
            limits:
              cpu: "10m"
              memory: "32Mi"
            requests:
              cpu: "5m"
              memory: "24Mi"